auto_sync = false
sync_address = "https://proliant.internal.metro.healthcare:8888"
style = "auto"
dialect = "us"
search_mode = "fuzzy"
filter_mode = "global"
filter_mode_shell_up_keybinding = "global"
